package com.sharenotifications.appEntities.enums;





public enum NotificationType {
	RENT_REQUEST_PENDING,
	RENT_REQUEST_ACCEPTED,
	RENT_REQUEST_REJECTED,
	BUY_REQUEST_PENDING,
	BUY_REQUEST_ACCEPTED,
	BUY_REQUEST_REJECTED,
	RETURN_REQUEST_PENDING,
	RETURN_REQUEST_ACCEPTED,
	RETURN_REQUEST_REJECTED,
}