var urls = {
	IN : "in",
	SIGN_IN : "signIn",
	SIGN_UP : "signUp",
	SIGN_OUT : "signOut",
	HOME : "home",
	GET_BOOK : "getBook",
	GET_ALL_BOOKS : "getAllBooks",
	GET_USER : "getUser",
	FILTER_BY_CATEGORY : "home/filterByCategory",
	FILTER_BY_SEARCH : "home/filterBySearch",
	ADD_BOOK : "home/addBook",
	VIEW_BOOK : "viewBook",
	CHECKOUT : "checkout",
	UPDATE_USER : "home/updateUser",
	VIEW_HISTORY : "home/viewHistory",
	GET_NOTIFICATIONS : "home/getNotifications",
	GET_SIMILAR_BOOKS : "viewBook/getSimilarBooks",
	ADD_BOOK_REQUEST : "checkout/addBookRequest",
	BOOK_RESPONSE : "bookResponse"
}